INSERT INTO Artist (Name) VALUES ('Alfred Hitchcock');
INSERT INTO dbo.Artist (Name) VALUES ('Stanley Kubrick');
INSERT INTO dbo.Artist (Name) VALUES ('Quentin Tarantino');
INSERT INTO dbo.Artist (Name) VALUES ('Lars von Trier');
INSERT INTO dbo.Artist (Name) VALUES ('Akira Kurosawa');
INSERT INTO dbo.Artist (Name) VALUES ('Guy Richie');
INSERT INTO dbo.Artist (Name) VALUES ('Andy Wachowski');
INSERT INTO dbo.Artist (Name) VALUES ('Steven Sielberg');
INSERT INTO dbo.Artist (Name) VALUES ('Sam Mendes');
INSERT INTO dbo.Artist (Name) VALUES ('Blake Edwards');
INSERT INTO dbo.Artist (Name) VALUES ('Brian De Palma');
INSERT INTO dbo.Artist (Name) VALUES ('Victor Fleming');
INSERT INTO dbo.Artist (Name) VALUES ('George Lucas');
INSERT INTO dbo.Artist (Name) VALUES ('Gore Verbinski');
INSERT INTO dbo.Artist (Name) VALUES ('David O. Russell');
INSERT INTO dbo.Artist (Name) VALUES ('Marc Webb');
INSERT INTO dbo.Artist (Name) VALUES ('Richard Linklater');
INSERT INTO dbo.Artist (Name) VALUES ('Adam Brooks');
INSERT INTO dbo.Artist (Name) VALUES ('Nicole Holofcener');
INSERT INTO dbo.Artist (Name) VALUES ('Will Gluck');
INSERT INTO dbo.Artist (Name) VALUES ('Edward Zwick');
INSERT INTO dbo.Artist (Name) VALUES ('Ivan Reitman');
INSERT INTO dbo.Artist (Name) VALUES ('Lone Scherfig');
INSERT INTO dbo.Artist (Name) VALUES ('Richard LaGravenese');
INSERT INTO dbo.Artist (Name) VALUES ('Lasse Hallström');
INSERT INTO dbo.Artist (Name) VALUES ('Peter Chelsom');
INSERT INTO dbo.Artist (Name) VALUES ('John Maybury');
INSERT INTO dbo.Artist (Name) VALUES ('Josh Boone');
INSERT INTO dbo.Artist (Name) VALUES ('Nick Cassavetes');
INSERT INTO dbo.Artist (Name) VALUES ('Michael Sucsy');
INSERT INTO dbo.Artist (Name) VALUES ('Joshua Michael Stern');
INSERT INTO dbo.Artist (Name) VALUES ('Jason Reitman');
INSERT INTO dbo.Artist (Name) VALUES ('Steven Soderbergh');
INSERT INTO dbo.Artist (Name) VALUES ('Stuart Blumberg');
INSERT INTO dbo.Artist (Name) VALUES ('David Fincher');
INSERT INTO dbo.Artist (Name) VALUES ('Wes Anderson');
INSERT INTO dbo.Artist (Name) VALUES ('Frank Darabont');
INSERT INTO dbo.Artist (Name) VALUES ('Sergio Corbucci');

INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 1, 'Psycho', 1960, 'Images/psycho-lrg-21.jpg');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 2, 'Barry Lindon', 1975, 'Images/barry-lyndon-0008134-I.jpg');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 2, 'A Clockwork Orange', 1971, 'Images/clockwork-orange-lrg-07.jpg');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 2, 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb', 1964, 'Images/dr-strangelove-lrg-23.jpg');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 3, 'Kill Bill: Vol. 1', 2003, 'Images/kill-bill-lrg-28.jpg');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 3, 'Pulp Fiction', 1994, 'Images/pulp-fiction-lrg-20.jpg');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 4, 'Melancholia', 2011, 'Images/melancholia-lrg-28.jpg');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 5, 'Seven Samurai', 1956, 'Images/seven-samurai-lrg-21.jpg');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 6, 'Snatch', 2000, 'Images/snatch-lrg-32.jpg');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 7, 'Matrix', 1999, 'Images/matrix-lrg-15.jpg');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 8, 'Jaws', 1975, 'Images/jaws-lrg-02.jpg');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 9, 'Skyfall', 2012, 'Images/james-bond-skyfall-blu-ray-screenshot-0061963-I-1920.jpg');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 37, 'Django', 1966, 'Images/django-lrg-30.jpg');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 10, 'Breakfast at Tiffanys ', 1961, 'Images/breakfast-at-tiffanys-lrg-27.jpg');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 11, 'Carrie', 1976, 'Images/carrie-lrg-09.jpg');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 12, 'Gone with the Wind', 1939, 'Images/gone-in-the-wind-lrg-16.jpg');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 13, 'Star Wars: Episode IV - A New Hope', 1977, 'Images/star-wars-IV-lrg-01.jpg');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 14, 'Pirates of the Caribbean', 2003, 'Images/pirates-of-the-carribean-lrg-23.jpg');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 15, 'American Hustle', 2013, 'Images/american-hustle-blu-ray-screenshot-0085366-I-1920.jpg');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 16, '(500) Days of Summer', 2009, 'Images/500_days_of_summer.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 17, 'Before Sunrise', 1995, 'Images/before_sunrise.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 18, 'Definitely, Maybe', 2008, 'Images/definitely_maybe.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 19, 'Enough Said', 2013, 'Images/enough_said.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 20, 'Friends with Benefits', 2011, 'Images/friends_with_benefits.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 21, 'Love & Other Drugs', 2010, 'Images/love_and_other_drugs.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 22, 'No Strings Attached', 2011, 'Images/no_strings_attached.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 23, 'One Day', 2011, 'Images/one_day.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 24, 'P.S. I Love You', 2007, 'Images/ps_i_love_you.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 25, 'Safe Haven', 2013, 'Images/safe_haven.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 26, 'Serendipity', 2001, 'Images/serendipity.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 27, 'The Edge of Love', 2008, 'Images/the_edge_of_love.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 28, 'The Fault in Our Stars', 2014, 'Images/the_fault_in_our_stars.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 29, 'The Notebook', 2004, 'Images/the_notebook.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 30, 'The Vow', 2012, 'Images/the_vow.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 31, 'Jobs', 2013, 'Images/jobs.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 32, 'Labor Day', 2013, 'Images/labor_day.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 4, 'Nymphomaniac', 2013, 'Images/nymfomaniac.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 33, 'Side Effects', 2013, 'Images/side_effects.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 34, 'Thanks for Sharing', 2012, 'Images/thanks_for_sharing.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 35, 'The Girl with the Dragon Tattoo', 2011, 'Images/the_girl_with_a_dragon_tattoo.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 36, 'The Grand Budapest Hotel', 2014, 'Images/the_grand_budapest_hotel.tiff');
INSERT INTO dbo.ArtWork (ArtWorkType, ArtistId, Name, Year, FileLocation) VALUES (0, 37, 'The Shawshank Redemption', 1994, 'Images/the_shawshank_redemption.tiff');

INSERT INTO dbo.GameQuestions (Name, IsGameMode) VALUES ('Stanley Kubrick movies', 'TRUE');
INSERT INTO dbo.GameQuestions (Name, IsGameMode) VALUES ('Tarantino movies', 'TRUE');
INSERT INTO dbo.GameQuestions (Name, IsGameMode) VALUES ('Romantic movies', 'TRUE');
INSERT INTO dbo.GameQuestions (Name, IsGameMode) VALUES ('Drama movies', 'TRUE');
INSERT INTO dbo.GameQuestions (Name) VALUES ('RandomGameQuestionsCodeGoesHere');


INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (1, 1);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (1, 2);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (1, 3);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (1, 4);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (1, 5);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (1, 6);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (3, 20);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (3, 21);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (3, 22);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (3, 23);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (3, 24);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (3, 25);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (3, 26);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (3, 27);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (3, 28);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (3, 29);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (3, 30);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (3, 31);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (3, 32);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (3, 33);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (3, 34);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 20);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 21);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 22);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 23);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 25);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 27);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 28);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 29);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 31);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 32);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 33);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 34);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 35);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 36);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 37);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 38);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 39);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 40);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 41);
INSERT INTO dbo.Question (GameQuestionsId, ArtWorkId) VALUES (4, 42);

