using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Domain;
using DomainLogic.IdentityModels;

namespace DAL.Interfaces
{
    public interface IUOW
    {
        //save pending changes to the data store
        void Commit();
        //Standard repos, autogenerated
        IEFRepository<DrawCategory> DrawCategories { get; }
        IEFRepository<Product> Products { get; }
        IEFRepository<ProductType> ProductTypes { get; }
        IEFRepository<Winning> Winnings { get; }
        IEFRepository<Bill> Bills { get; }
        IUserRepository Users { get; }
        IUserRoleRepository UserRoles { get; }
        IRoleRepository Roles { get; }
		IUserClaimRepository UserClaims { get; }
		IUserLoginRepository UserLogins { get; }
        IDrawRepository Draws { get; }
        IUserInDrawRepository UserInDraws { get; }
        IDrawDurationRepository DrawDurations { get; }
        IDrawPriorityRepository DrawPriorities { get; }
        IDrawSizeRepository DrawSizes { get; }
    }
}
